service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          method: get
          path: /products/{productId}
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          method: get
          path: /products
